language: csharp
solution: Sudoku.sln
install:
  - nuget restore Sudoku.sln
  - sudo apt-get install nunit-console
script:
  - xbuild /p:Configuration=Release Sudoku.sln
  - nunit-console ./Tests/bin/Release/Tests.dll

